services:
  postgres:
    image: postgres:14-alpine
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql